hide_download: true
hide_download_original: null
leftnav:
- identifier: 8fbc95c7-eb9a-0ded-b0c9-021a5fb0bf03
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 8362f5b1-ea90-385d-89b5-860742366818
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 82960cb4-abdb-c683-77d5-9728754c344f
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: e5d05ba9-aaa6-aa01-b6c7-3f3c7fcbb362
  name: Selected Videos
  pageRef: /pages/selected-videos
  weight: 40
- identifier: e5b98993-7502-62d1-d4ec-b7760924db51
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
